AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: NodeJS proxy api server ...
Resources:
  ApiProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/httpproxy.handler
      Runtime: nodejs12.x
      Description: API!!!
      MemorySize: 1024
      Timeout: 10
      Events:
        ProxyApiGreedy:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

  Logger:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/lambdas/logger.handler
      Runtime: nodejs12.x
      Description: API!!!
      MemorySize: 1024
      Timeout: 10
